### ISSUE TITLE
Issues to launch bokken

### ISSUE THREAD

**Issue by alvarofe** [inguma/bokken#14]
When I run bokken I get the following output

```
alvaro_fe@macbook  ~/Projects/Reverse/bokken   master  python bokken.py
        Python version...       OK
        Python version...       OK
        Radare availability...  OK
        GTK UI dependencies...  OK
        GtkSourceView2...       OK
        Graphviz binaries...    OK
Starting bokken 1.9-dev, running on:
  Python version:
    2.7.10 (default, May 26 2015, 13:01:57)
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
  GTK version: 2.24.28
  PyGTK version: 2.24.0

Traceback (most recent call last):
  File "bokken.py", line 76, in <module>
    bokken()
  File "bokken.py", line 71, in bokken
    'radare' if args.radare else '',
  File "/Users/alvaro_fe/Projects/Reverse/bokken/ui/main.py", line 395, in main
    BokkenGTKClient(target, backend)
  File "/Users/alvaro_fe/Projects/Reverse/bokken/ui/main.py", line 96, in __init__
    dialog = file_dialog.FileDialog(self.target, True)
  File "/Users/alvaro_fe/Projects/Reverse/bokken/ui/file_dialog.py", line 41, in __init__
    ui.gtk2.common.set_bokken_icon(self)
  File "/Users/alvaro_fe/Projects/Reverse/bokken/ui/gtk2/common.py", line 42, in set_bokken_icon
    obj.set_icon_from_file(lib.common.datafile_path('bokken.svg'))
GError: No se pudo reconocer el formato de imagen del archivo «/Users/alvaro_fe/Projects/Reverse/bokken/ui/data/bokken.svg»
```

I don't know if I'm missing some dependencies

Thanks in advanced and great work :)

**Comment by hteso** [comment]
Hi!

Yep, that is a know issue of PyGtk on OSX with Homebrew... I don't remember how to solve it, I'm afraid the best approach is to search Google for the error message (in english).

For the next release we will convert all the SVG to other format to avoid this problem. I will create an issue with this talk :)

Also, if you find the solution, please post it here so I can add to the installation instructions on the web.

Sorry for not being able to help you more :(

**Comment by alvarofe** [comment]
Don't worry. I will try to fix it if I can jeje and I let you know how here :)

**Comment by Jo-Con-El** [comment]
I don't have homebrew installed, but could you adjust the path, run it and see if this fixes it?

GDK_PIXBUF_MODULEDIR=$HOMEBREW/lib/gdk-pixbuf-2.0/2.10.0/loaders gdk-pixbuf-query-loaders --update-cache

This is from https://github.com/Homebrew/homebrew/issues/13786.

**Comment by Jo-Con-El** [comment]
Install librsvg first.  Maybe that will do it.  From a similar issue:

> "Did you try installing libsvg before you built cairo, pixman, and the rest? Because libsvg comes from the same developer, it likely integrates well. It's worth mentioning that our current version of cairo-1.10.2 is a bit old, and we are about to pull the trigger on cairo-1.12.2."

**Comment by alvarofe** [comment]
None of them worked @Jo-Con-El but anyway I will try to find a solution or install PyGtk from source instead from Homebrew. If I find something I will share

Thanks :)

**Comment by Jo-Con-El** [comment]
No problem, keep us updated!

You can also wait for another month or so (hopefully) because we are moving away from PyGTK and embracing the beautiful world of GObject and GTK+3!  There's still no commits in mercurial/git because we try to keep the tip stable at all times, and Bokken will be "Brokken" for some weeks until we iron out all the bugs. :smile:

**Comment by Jo-Con-El** [comment]
@alvarofe, any advance?  We are stuck with almost no manpower in the project and the GTK+3 port is taking more time than expected.

**Comment by alvarofe** [comment]
I didn't try it, shame on me :(. I was thinking that the moving from PyGTK and GTK+3 would be faster. I add this to my TODO and swear that I'll dedicate some time this weekend.

**Comment by hteso** [comment]
@alvarofe Tomorrow we will release the Windows installer for Bokken 1.8; it worked perfectly in all our tests so, hopefully, it will work for you as well :)
