### ISSUE TITLE
Failed to launch on Windows

### ISSUE THREAD

**Issue by CheyiLin** [inguma/bokken#19]
Hi,
I got following error when launching Bokken on Windows:

```
D:\Desktop\Bokken\bokken-1.8>python bokken.py
        Python version...Traceback (most recent call last):
  File "bokken.py", line 76, in <module>
    bokken()
  File "bokken.py", line 68, in bokken
    import ui.main as main
  File "D:\Desktop\Bokken\bokken-1.8\ui\main.py", line 27, in <module>
    dependency_check.check_all()
  File "D:\Desktop\Bokken\bokken-1.8\ui\dependency_check.py", line 27, in check_all
    python_version()
  File "D:\Desktop\Bokken\bokken-1.8\ui\dependency_check.py", line 40, in python_version
    print(common.console_color('\tOK', 'green'))
  File "D:\Desktop\Bokken\bokken-1.8\lib\common.py", line 102, in console_color
    return('%s%s%s' % (ansi_code[color], string, ansi_code['white']))
TypeError: list indices must be integers, not str
```

I think it is caused by this:
``` python
if sys.platform == "win32":
        # No color for you today!
        ansi_code = map(lambda x:'', ansi_code)
```
which turns `ansi_code` from a `dict` into a `list`.

Hope you could fix it, thanks.

**Comment by Jo-Con-El** [comment]
This was fixed in 4ebbd03 by returning the original string and not messing up with the ansi_codes dictionary.
